name: OilProducePlugin
version: 1.17.1
author: gabjuho
main: com.gabjuho.oilproduceplugin.Main
api-version: 1.17
commands:
  석유시간:
    description: 석유 생성까지 남은 시간을 알려주는 커맨드
    usage: /<command>
  석유위치:
    description: 석유 생성기의 위치를 XYZ 좌표로 표시해주는 커맨드
    usage: /<command>